### ISSUE TITLE
個人推薦 Consolas + Fira Code 的連字 混合起來的字體

### ISSUE THREAD

**Issue by bluelovers** [biezhi/code-fonts#1]
個人推薦 Consolas + Fira Code 的連字 混合起來的字體

**Comment by biezhi** [comment]
@bluelovers 怎么混合?

**Comment by bluelovers** [comment]
這個可以把任何你喜歡的字體 加上 Fira Code 的連字
https://github.com/ToxicFrog/Ligaturizer

這裡有合併好的
[LigaConsolas.zip](https://github.com/biezhi/code-fonts/files/2237615/LigaConsolas.zip)

**Comment by biezhi** [comment]
@bluelovers get!
